services:
  - type: web
    name: recicla-gana            # nombre de tu servicio
    env: docker
    plan: free
    region: oregon                # o tu región favorita
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ecodata
      - key: DB_NAME
        value: ecodata
      - key: DB_USER
        fromDatabase:
          name: ecodata
          property: user
      - key: DB_PASS
        fromDatabase:
          name: ecodata
          property: password

databases:
  - name: ecodata                 # nombre de tu base de datos
    engine: mysql
    plan: free
