# render.yaml
services:
  - type: web
    name: recicla-gana
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ecodata
      - key: DB_PORT                # << aquí!
        fromDatabase:
          name: ecodata
          property: port
      - key: DB_NAME
        value: ecodata
      - key: DB_USER
        fromDatabase:
          name: ecodata
          property: user
      - key: DB_PASS
        fromDatabase:
          name: ecodata
          property: password

databases:
  - name: ecodata
    engine: mysql
    plan: free
