services:
  - type: web
    name: recicla-gana
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ecodata
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ecodata
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ecodata
          property: database
      - key: DB_USER
        fromDatabase:
          name: ecodata
          property: user
      - key: DB_PASS
        fromDatabase:
          name: ecodata
          property: password
